name: build
on:
  workflow_dispatch:
    inputs:
       ROM_URL:
         description: 'ROM URL'
         required: true
         default: ''
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Build
        run: |
          sudo bash build.sh ${{ github.event.inputs.ROM_URL }}
          echo "rom_name=$(find ${GITHUB_WORKSPACE} -type f -name "HAYDN*.zip")" >> "${GITHUB_ENV}"
          
      - name: Upload To Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v2.2.2
        with:
          target: ${{ env.rom_name }}
          credentials: ${{ secrets.credentials }}
          parent_folder_id: ${{ secrets.folderId }}
